export const Q_KEYS = {
  BRANCHES: "branches",
  SERVICES: "services",
  STAFFS: "staffs",
  APPOINTMENTS: "appointments",
  ACTIVITY_LOGS: "activity-logs",
  SMS_LOGS: "sms-logs",
  SETTINGS: "settings",
  CURRENT_USER: "current-user",
  BUSINESSES: "businesses",
  REMINDER_CONFIGS: "reminder-configs",
  APPOINTMENT_COUNTS: "appointment-counts",
  ME: "me",
  ADMIN_BUSINESSES: "admin-businesses",
  ADMIN_SMS_BALANCE: "admin-sms-balance",
  ANALYTICS: "analytics",
  UPDATE_STATUS: "update-status",
  UPDATE: "update",
  DELETE: "delete",
  CREATE: "create",
  ALL: "all",
  TODAY: "today",
  UPCOMING: "upcoming",
  PAYMENTS: "payments",
};
